name: Set vcpkg variables

inputs:
  os:
    description: "OS name"
    required: true
  qt-version:
    description: "Qt version to install"
    required: true
outputs:
  vcpkg-packages:
    description: "Packages to install via vcpkg"
    value: ${{ steps.vcpkg-packages.outputs.value }}
  vcpkg-cachekey:
    description: "Cache key for vcpkg"
    value: ${{ steps.vcpkg-cachekey.outputs.value }}

runs:
  using: "composite"
  steps:
    - id: vcpkg-packages
      run: echo "value=$(python3 ${{ github.workspace }}/scripts/vcpkgPackages.py qt${{ inputs.qt-version }} ${{ inputs.os }})" # >> ${GITHUB_OUTPUT}
      shell: pwsh
    - id: vcpkg-cachekey
      run: echo "value=$(python3 ${{ github.workspace }}/scripts/vcpkgCacheKey.py qt${{ inputs.qt-version }} ${{ inputs.os }})" # >> ${GITHUB_OUTPUT}
      shell: pwsh
