name: 'Common setup'
description: 'Setup common deps and tools'
inputs:
  os:
    required: true
  qt:
    required: true
  triplet:
    required: true

runs:
  using: "composite"
  steps:
    - uses: lukka/get-cmake@latest

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ inputs.os }}-QtCache-${{ inputs.qt }}
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        aqtversion: ==2.0.0
        version: '${{ inputs.qt }}'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Set outputs
      run: |
        echo "::set-output name=dependencies::$(python3 ${{ github.workspace }}/scripts/vcpkgPackages.py qt${{ inputs.qt }} ${{ inputs.os }}-latest)"
        echo "::set-output name=cacheKey::$(python3 ${{ github.workspace }}/scripts/vcpkgCacheKey.py qt${{ inputs.qt }} ${{ inputs.os }}-latest)"
      id: set-outputs
      shell: bash
        
    - uses: lukka/run-vcpkg@v7.3
      with:
        vcpkgDirectory: ${{ github.workspace }}/ext/vcpkg
        appendedCacheKey: ${{ steps.set-outputs.outputs.cacheKey }}
        vcpkgTriplet: ${{ inputs.triplet }}
        vcpkgArguments: ${{ steps.set-outputs.outputs.dependencies }}
        doNotUpdateVcpkg: true
      if: steps.set-outputs.outputs.dependencies != 'nil'
