runs:
  using: composite
  steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-5.15.1

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v2
      with:
        path: ./vcpkg
        key: ${{ runner.os }}-vcpkg

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.1'
        modules: 'qtvirtualkeyboard'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Clone vcpkg
      run: git clone https://github.com/microsoft/vcpkg
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Setup vcpkg
      run: |
        cd vcpkg
        git checkout 896498fdbae91d5f97bfffcadef21b066277fcf2
        ./bootstrap-vcpkg.sh

    - name: Install dependencies in vcpkg
      run: ./vcpkg/vcpkg install boost-di:x64-linux