#ifndef QTPIDECKCOMMON_GLOBAL_H
#define QTPIDECKCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTPIDECKCOMMON_LIBRARY)
#  define QTPIDECKCOMMON_EXPORT Q_DECL_EXPORT
#else
#  define QTPIDECKCOMMON_EXPORT Q_DECL_IMPORT
#endif

#ifndef QTPI4_VERSION
#define QTPI4_VERSION QT_VERSION_CHECK(5, 11, 3)
#endif
#ifndef QT_MIN_TESTED_VERSION
#define QT_MIN_TESTED_VERSION QT_VERSION_CHECK(5, 15, 1)
#endif

#if (QT_VERSION > QTPI4_VERSION && QT_VERSION < QT_MIN_TESTED_VERSION)
#error "New rasberrypi 4 qt version detected(?)"
#endif

#endif // QTPIDECKCOMMON_GLOBAL_H
