name: Install dependencies

inputs:
  os:
    description: "OS name"
    required: true
  qt-version:
    description: "Qt version to install"
    required: true
  vcpkg-packages:
    description: "Packages to install via vcpkg"
    required: true
  vcpkg-cachekey:
    description: "Cache key for vcpkg"
    required: true
  vcpkg-triplet:
    description: "Triplet for vcpkg"
    required: true

runs:
  using: "composite"
  steps:
    - uses: lukka/get-cmake@latest
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        dir: ${{ github.workspace }}/Qt
        version: '${{ inputs.qt-version }}'
        cache: true
        cache-key-prefix: ${{ inputs.os }}-QtCache-${{ inputs.qt-version }}
    - uses: lukka/run-vcpkg@v7.3
      with:
        vcpkgDirectory: ${{ github.workspace }}/ext/vcpkg
        appendedCacheKey: ${{ inputs.vcpkg-cachekey }}
        vcpkgTriplet: ${{ inputs.triplet }}
        vcpkgArguments: ${{ inputs.vcpkg-packages }}
        doNotUpdateVcpkg: true
      if: steps.set-outputs.outputs.dependencies != 'nil'
