name: Test

inputs:
  os:
    description: "OS name"
    required: true
  qt-version:
    description: "Qt version to install"
    required: true
outputs:
  vcpkg-packages:
    description: "Packages to install via vcpkg"
    value: ${{ steps.vcpkg-package.outputs.packages }}

runs:
  using: "composite"
  steps:
    - uses: lukka/get-cmake@latest
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        dir: ${{ github.workspace }}/Qt
        version: '${{ inputs.qt-version }}'
        cache: true
        cache-key-prefix: ${{ inputs.os }}-QtCache-${{ inputs.qt-version }}w
    - run: ${{ github.workspace }}/scripts/vcpkgPackages.py qt${{ inputs.qt-version }} ${{ inputs.os }}
      shell: python
    - run: ${{ github.workspace }}/scripts/vcpkgCacheKey.py qt${{ inputs.qt-version }} ${{ inputs.os }}
      shell: python
