name: Common lib workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  QTPI: 5.11.3
  QT5: 5.15.5
  QT6: 6.2.1
  VULKAN_VER: 1.3.224
  VULKAN_VER_FULL: 1.3.224.0

jobs:
  done:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo "DONE"
