name: qmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ./Qt
          key: ${{ runner.os }}-QtCache-5.15.1

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
          path: ./vcpkg
          key: ${{ runner.os }}-vcpkg

      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          modules: 'qtvirtualkeyboard'
          dir: ./
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Setup vcpkg
        run: |
          cd vcpkg
          git checkout 896498fdbae91d5f97bfffcadef21b066277fcf2
          ./bootstrap-vcpkg.sh

      - name: Install dependencies in vcpkg
        run: ./vcpkg/vcpkg install boost-di:x64-linux

      - name: Run qmake
        run: |
          mkdir build && cd build
          qmake ..
        env:
          VCPKG_PACKAGES: ${{ env.GITHUB_WORKSPACE }}/vcpkg/installed/x64-linux
      - name: Build project
        run: |
          cd build
          make -j3  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ./Qt
          key: ${{ runner.os }}-QtCache-5.15.1

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v2
        with:
          path: ./vcpkg
          key: ${{ runner.os }}-vcpkg

      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          modules: 'qtvirtualkeyboard'
          dir: ./
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Setup vcpkg
        run: |
          cd vcpkg
          git checkout 896498fdbae91d5f97bfffcadef21b066277fcf2
          ./bootstrap-vcpkg.sh

      - name: Install dependencies in vcpkg
        run: ./vcpkg/vcpkg install boost-di:x64-linux

      - name: Run qmake
        run: |
          mkdir build && cd build
          qmake ..
        env:
          VCPKG_PACKAGES: ${{ env.GITHUB_WORKSPACE }}/vcpkg/installed/x64-linux
      - name: Test project
        run: |
          cd build
          LD_LIBRARY_PATH=$PWD/QtPiDeckCommon/ make -j3 check TESTARGS="-platform offscreen"
