name: qmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          modules: 'qtvirtualkeyboard'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Run cmake
        run: |
          cmake .. -G Ninja
      - name: Build project
        run: |
          ninja
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          modules: 'qtvirtualkeyboard'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Run cmake
        run: |
          pwd
          cmake .. -G Ninja
      - name: Build project
        run: |
          ninja
      - name: Test project
        run: ctest
        env:
          LD_LIBRARY_PATH: ./QtPiDeckCommon
          TESTARGS: -platform offscreen
