name: qmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          modules: 'qtvirtualkeyboard'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Run qmake
        run: |
          mkdir build && cd build
          qmake ..
      - name: Build project
        run: |
          cd build
          make -j3  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          modules: 'qtvirtualkeyboard'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Run qmake
        run: |
          mkdir build && cd build
          qmake ..
      - name: Build project
        run: |
          cd build
          LD_LIBRARY_PATH=$PWD/QtPiDeckCommon/ make -j3 check TESTARGS="-platform offscreen"
