name: qmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps
      
      - name: Run qmake
        run: |
          mkdir build && cd build
          qmake ..
        env:
          VCPKG_PACKAGES: ${{ env.GITHUB_WORKSPACE }}/vcpkg/installed/x64-linux
      - name: Build project
        run: |
          cd build
          make -j3  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps

      - name: Run qmake
        run: |
          mkdir build && cd build
          qmake ..
        env:
          VCPKG_PACKAGES: ${{ env.GITHUB_WORKSPACE }}/vcpkg/installed/x64-linux
      - name: Test project
        run: |
          cd build
          LD_LIBRARY_PATH=$PWD/QtPiDeckCommon/ make -j3 check TESTARGS="-platform offscreen"
